apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Leomendoza13/eks-scalable-devops-platform
    targetRevision: readmev2
    path: kubernetes/overlays/dev/networking
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false 